### ISSUE TITLE
Flemington Racecourse line is missing

### ISSUE THREAD

**Issue by lachlanwgordon** [stevage/trainle#6]
There are two stations missing from stations.json:
 - Showgrounds
 - Flemington Racecourse

Sure, they're not open very often but they're still real train stations so I think they should be included. 

There is a quirk in the current station data that all the stations that are on the Flemington Racecourse line and also on another line are listed as being on the Flemington line, this is causing errors when constructing the graph because there's no such thing as a Flemington line.

Proposed Solution has 2 parts:
1. Add the missing stations in stations.json
2. Update the 6 stations that currently claim to be on the "Flemington" line to say "Flemington Racecourse" instead.

Note:
I don't like horse racing and I have mixed feelings about the show. None the less I think they should open the line for regular service. This would also involve reopenning Ascot Vale Road Goods Platform Railway Station, extending the line to the airport and adding stations at Highpoint and in the abondonned Maribyrnong defence site.

**Comment by gamer191** [comment]
This issue and issue #2 seem to have both gotten PRs but not been closed for some reason
